# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_auto_20180321_1721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=set([('event', 'invitee')]),
        ),
    ]
