# Generated by Django 2.1.2 on 2018-10-09 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_auto_20180330_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='invited_events',
            field=models.ManyToManyField(blank=True, null=True, through='invitations.Rsvp', to='invitations.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(blank=True, through='invitations.Rsvp', to=settings.AUTH_USER_MODEL),
        ),
    ]
